### ISSUE TITLE
binary to/from hex

### ISSUE THREAD

**Issue by jimmywarting** [jessetane/hex-string#2]
Unrelated but do you know any fast hex to/from binary? (possible with a lookup table as well?)

```js
// Want to replace this:
Buffer.from(str, 'binary').toString('hex')
Buffer.from(str, 'hex').toString('binary')
```

(trying to remove the buffer module from my browser bundle...)

**Comment by jessetane** [comment]
latin1... but why?

**Comment by jessetane** [comment]
in any case this module is "dumb" wrt to the encoding of your binary data, so it shouldn't matter if it's latin1, utf8, etc

**Comment by jessetane** [comment]
from glancing at the buffer source, it looks like js string <> latin1 is pretty straight forward:
read: https://github.com/feross/buffer/blob/master/index.js#L1043
write: https://github.com/feross/buffer/blob/master/index.js#L1758
